apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: whizspace
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:7.68.0
    command: ['sh', '-c', 'tail -f /dev/null']
    securityContext:
      runAsUser: 0
      privileged: true
