apiVersion: v1
kind: Pod
metadata:
  name: multipod
  labels:
    environment: dev
spec:
  containers:
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80
  - name: tomcatcontainer
    image: tomcat
    ports:
    - containerPort: 8080
    
---

apiVersion: v1
kind: Service
metadata:
  name: multiport-service
spec:
  type: ClusterIP
  selector:
    environment: dev
  ports:
  - name: nginxport
    protocol: TCP
    port: 8000
    targetPort: 80
  - name: tomcatport
    protocol: TCP
    port: 8001
    targetPort: 8080
