apiVersion: v1
kind: Pod
metadata:
  name: localhostmysql
  labels:
    app: db
spec:
  containers:
  - image: mysql:5.7
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password 
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: mysql-hostpath-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-hostpath-storage
    hostPath:
      path: "/mnt/data_my"
      type: DirectoryOrCreate
