apiVersion: v1
kind: Pod
metadata:
  name: nginxpod2
  labels:
    environment: staging
    tier: frontend
spec:
  containers:
  - name: nginxcontainer2
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
spec:
  type: ClusterIP
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 80
