apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: whizspace
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: default-scheduler
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
