apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    environment: staging
    tier: frontend
spec:
  containers:
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
