apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: whizspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      hostname: ubuntu-test1
      containers:
      - name: ubuntu-container
        image: ubuntu
        command: ["/bin/sh"]
        args:
        - "-c"
        - "echo the pod is running; while true; do echo .; sleep 1; done"
        volumeMounts:
        - name: secretvol
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
      - name: secretvol
        secret:
          secretName: mysecret
