apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv
  labels:
    env: staging
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: whizlabs
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/pvcdir
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc
  namespace: whizspace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: whizlabs
  selector:
    matchLabels:
      env: staging
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: whizspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu
        command: ["/bin/sh"]
        args:
        - "-c"
        - "echo the pod is running; while true; do echo .; sleep 1; done"
        volumeMounts:
        - name: ubuntu-pvc-storage
          mountPath: /tmp/data
      volumes:
      - name: ubuntu-pvc-storage
        persistentVolumeClaim:
          claimName: testpvc
