apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin1
  namespace: whizspace

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rolebind
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: admin1
  namespace: whizspace
